# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MODEL_fix_1.py
# Created on: 2024-02-28 09:34:28.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
import Tkinter as tk
from tkinter import messagebox
import tkFileDialog as filedialog
from tkFileDialog import askopenfilename
       
       
root = tk.Tk()
root.withdraw()
messagebox.showinfo("showinfo","Please input your DTM Raster")
raster_proc = filedialog.askopenfilename()
messagebox.showinfo("showinfo","Please insert folder to store result")
gdb_location = filedialog.askdirectory()

root.destroy

list_directory = ["last_result","geodatabase"]

last_result = os.path.join(gdb_location,list_directory[0])
geodatabase_loc = os.path.join(gdb_location,list_directory[1])

os.makedirs(last_result)
os.makedirs(geodatabase_loc)

# Process: Create File GDB
outputgdb = "flow_acc_dir.gdb"
arcpy.CreateFileGDB_management(geodatabase_loc, outputgdb, "CURRENT")

geodatabase_acc_dir = os.path.join(geodatabase_loc,outputgdb)

# Local variables:
acc_dir_gdb = gdb_location
arcpy.CheckOutExtension("Spatial")
fill_1 = os.path.join(geodatabase_acc_dir,"fill_1")
Flow_dir2 = os.path.join(geodatabase_acc_dir,"Flow_dir2")
flow_acc3 = os.path.join(geodatabase_acc_dir,"Flow_acc3")
rast_calc4 = os.path.join(geodatabase_acc_dir,"rast_calc4")
stream_order5 = os.path.join(geodatabase_acc_dir,"stream_order5")
rast_pl_flow_acc6_shp = os.path.join(last_result,"flow_accumulation")
rast_pg_flow_dir2__shp = os.path.join(last_result,"flow_direction")

Parallel_Processing_Factor ="0"
Parallel_Processing_Factor__2_ = "0"
Parallel_Processing_Factor__3_ = "0"
Parallel_Processing_Factor__4_ = "0"

# Process: Fill
tempEnvironment0 = arcpy.env.parallelProcessingFactor
arcpy.env.parallelProcessingFactor = Parallel_Processing_Factor
arcpy.gp.Fill_sa(raster_proc, fill_1, "")
arcpy.env.parallelProcessingFactor = tempEnvironment0

# Process: Flow Direction
tempEnvironment0 = arcpy.env.parallelProcessingFactor
arcpy.env.parallelProcessingFactor = Parallel_Processing_Factor__2_
arcpy.gp.FlowDirection_sa(fill_1, Flow_dir2, "NORMAL", "", "D8")
arcpy.env.parallelProcessingFactor = tempEnvironment0

# Process: Flow Accumulation
tempEnvironment0 = arcpy.env.parallelProcessingFactor
arcpy.env.parallelProcessingFactor = Parallel_Processing_Factor__3_
arcpy.gp.FlowAccumulation_sa(Flow_dir2, flow_acc3, "", "FLOAT", "D8")
arcpy.env.parallelProcessingFactor = tempEnvironment0

# Process: Raster Calculator
tempEnvironment0 = arcpy.env.parallelProcessingFactor
arcpy.env.parallelProcessingFactor = Parallel_Processing_Factor__4_
expression = "Con(\"flow_acc3\" > 25000, 1, 0)"
arcpy.gp.RasterCalculator_sa(expression, rast_calc4)
arcpy.env.parallelProcessingFactor = tempEnvironment0

# Process: Stream Order
arcpy.gp.StreamOrder_sa(rast_calc4, Flow_dir2, stream_order5, "STRAHLER")

# Process: Raster to Polyline
tempEnvironment0 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Disabled"
tempEnvironment1 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Disabled"
arcpy.RasterToPolyline_conversion(stream_order5, rast_pl_flow_acc6_shp, "ZERO", "0", "SIMPLIFY", "VALUE")
arcpy.env.outputZFlag = tempEnvironment0
arcpy.env.outputMFlag = tempEnvironment1

# Process: Raster to Polygon
tempEnvironment0 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Disabled"
tempEnvironment1 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Disabled"
arcpy.RasterToPolygon_conversion(Flow_dir2, rast_pg_flow_dir2__shp, "SIMPLIFY", "VALUE", "SINGLE_OUTER_PART", "")
arcpy.env.outputZFlag = tempEnvironment0
arcpy.env.outputMFlag = tempEnvironment1


